# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config.json', '.'),
        ('station_codes.json', '.'),
        ('ui/gui', 'ui/gui'),
        ('notification', 'notification'),
        ('services', 'services'),
        ('core', 'core'),
        ('logger', 'logger'),
        ('config', 'config'),
        ('utils', 'utils'),
        ('railway.ico', '.'),
    ],
    hiddenimports=[
        'PySide6',
        'PySide6.QtWidgets',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'requests',
        'prettytable',
        'pypinyin',
        'pypinyin.pinyin_data',
        'pypinyin.phrases_dict',
        'pypinyin.constants',
        'services.favorite_service',
        'services.cache_service',
        'services.station_search_service',
        'services.monitor_manager',
        'services.query_service',
        'notification.manager',
        'notification.base',
        'notification.channels',
        'core.ticket_api',
        'core.ticket_parser',
        'core.train_classifier',
        'core.time_filter',
        'logger.ticket_logger',
        'logger.query_history',
        'config.config_manager',
        'ui.gui.main_window',
        'ui.gui.filter_panel',
        'ui.gui.workers',
        'ui.gui.price_detail_dialog',
        'ui.gui.query_result_widget',
        'utils',
        'utils.time_utils',
        'utils.constants',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='CRTicketMonitor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='railway.ico',
)
